### ISSUE TITLE
Wireless Soil Moisture Sensor PS-3228 Compatibility

### ISSUE THREAD

**Issue by ParmaJonEman** [PASCOscientific/pasco_python#2]
The soil moisture sensor is listed as "testing" under compatibility, but it does not work at all. It gives me an error about decoding the data any time I take a measurement from the sensor. Are there any plans to make this sensor work with this library, or any other way to interface the sensor with a Raspberry Pi?

**Comment by jonathanhanna** [comment]
Supporting the Wireless Soil Moisture Sensor isn't currently on our roadmap. It shouldn't have been on the "Testing" list. There also isn't any alternative way to interface the sensor with a Raspberry Pi. I'm sorry about the miscommunication.

Thank you for bringing this to our attention. I'll make a note about your interest in support of this sensor when we consider future improvements to the library.

Jonathan Hanna
Product Manager
PASCO scientific
