### ISSUE TITLE
'CodeNodeDevice' object has no attribute '_send_command'

### ISSUE THREAD

**Issue by fucksophie** [PASCOscientific/pasco_python#3]
This bug happens every time I try doing anything with the //Code.Node.

`AttributeError: 'CodeNodeDevice' object has no attribute '_send_command'`

**Comment by feraco** [comment]
I have the same problem.

**Comment by crichards-pasco** [comment]
This is fixed in the new version [0.3.65](https://pypi.org/project/pasco/0.3.65/).
