### ISSUE TITLE
How to import the library?

### ISSUE THREAD

**Issue by yuchenglim04** [PASCOscientific/pasco_python#4]
`from src.pasco.pasco_ble_device import PASCOBLEDevice `

does not work for me. Instead, this works:

`pasco.pasco_ble_device import PASCOBLEDevice `

Why is this so?

Is it because of this?

```
from src.pasco.pasco_ble_device import PASCOBLEDevice 
# src is necessary until pip repository is updated
```

**Comment by crichards-pasco** [comment]
Yes, thanks for bringing this to our attention! The documentation has been updated.
As you've pointed out, you can import the pasco library like any other that you have installed via pip.
Here are a couple of other examples:
`import pasco`
`from pasco import PASCOBLEDevice`
